version: '3'
services:
  jupyter:
    build: 
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./work:/work
    ports:
      - 8888:8888
    command: "jupyter lab --notebook-dir=/work"