version: '3'
services:
  jupyter:
    build: 
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./work:/home/yokai/src
    ports:
      - 8888:8888
    command: "start-notebook.sh --NotebookApp.token="